### ISSUE TITLE
Vignette Build Issues

### ISSUE THREAD

**Issue by gabrielodom** [torongs82/Bioc2019_PanCancerStudy#1]
## Issue 1:

     Quitting from lines 81-148 (Bioc2019_workshop.Rmd) 
       Error: processing vignette 'Bioc2019_workshop.Rmd' failed with diagnostics:
       I couldn't find all the files from the query. Please check if the directory parameter is
    right or `GDCdownload` downloaded the samples.

Guess: this package vignette requires external data.

**Comment by gabrielodom** [comment]
Also, unless the package is optional, we use `library()` to attach a package namespace, not `require()`.
See Yihui Xie's blog post about this: https://yihui.name/en/2014/07/library-vs-require/

**Comment by gabrielodom** [comment]
Still Issue 1:

when I execute the `GDCdownload()` call, the download issues this repeated warning:

    cannot create file
    './inst/extdata/TCGAanalysis/GDCdata/TCGA-BRCA/TCGA-BRCA/legacy/Gene_expression/Gene_expression_quantification/a21e0872-777a-44c3-a135-a52a5d7775ed/unc.edu.461cbf67-a11d-4411-95b5-cf83ecf05d02.1283313.rsem.genes.results'
    reason 'No such file or directory'

**Comment by gabrielodom** [comment]
Still Issue 1

    BRCARnaseqSE <- GDCprepare(query_down, directory = DataDir)

errors with

    I couldn't find all the files from the query. Please check if the directory parameter
    is right or `GDCdownload` downloaded the samples.

**Comment by gabrielodom** [comment]
@torongs82 added the `BRCARnaseqSE` data set to the package, and now we can avoid this issue.

**Comment by gabrielodom** [comment]
## Issue 2:

On line 474 (Functional Enrichment Analysis section):

    require(MoonlightR)
    data(DEGsmatrix)
    dataFEA <- FEA(DEGsmatrix = DEGsmatrix)
    dataFEA_filt <- dataFEA[dataFEA$FDR < 0.01,]
    dataFEA_filt <- dataFEA_filt[abs(dataFEA_filt$Moonlight.Z.score) > 1,]

We get the following error:

    Error in abs(dataFEA_filt$Moonlight.Z.score) : non-numeric argument to mathematical function

**Comment by torongs82** [comment]
@gabrielodom can you try to install the latest version of MoonlightR from github https://github.com/ibsquare/MoonlightR/ ? thank you

**Comment by gabrielodom** [comment]
No. BioC2019 requires stable build packages. per Levi's instruction, we should depend on as little from GitHub as possible.

Is there a way to run this code from the stable MoonlightR build on Bioconductor?
